<?php 

declare(strict_types=1);

namespace App\DataFixtures\Demo\Service\DataProvider;

use App\Enum\Service\ServiceCategory;

class ServiceDataProvider
{
    /** @return mixed[] */
    public static function getData(): array
    {
        return [
            [
                'organization_reference' => 'organization1',
                'name' => 'Manicure hybrydowy',
                'description' => 'Stylizacja paznokci lakierem hybrydowym.',
                'category' => ServiceCategory::NAILS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 90.00,
                'created_at' => '2025-05-13T12:20+00:00',
                'updated_at' => '2025-05-13T12:20+00:00',
            ],
            [
                'organization_reference' => 'organization1',
                'name' => 'Regulacja brwi i henna',
                'description' => 'Zabieg podkreślający kształt i kolor brwi.',
                'category' => ServiceCategory::LASHES_AND_BROWS->value,
                'duration' => 'P0Y0M0DT0H45M',
                'estimated_price' => 60.00,
                'created_at' => '2025-05-13T12:20+00:00',
                'updated_at' => '2025-05-13T12:20+00:00',
            ],
            [
                'organization_reference' => 'organization1',
                'name' => 'Pedicure klasyczny',
                'description' => 'Zabieg pielęgnacyjny stóp i paznokci.',
                'category' => ServiceCategory::NAILS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 100.00,
                'created_at' => '2025-05-13T12:20+00:00',
                'updated_at' => '2025-05-13T12:20+00:00',
            ],
            [
                'organization_reference' => 'organization2',
                'name' => 'Masaż relaksacyjny całego ciała',
                'description' => 'Zabieg odprężający z olejkami aromatycznymi.',
                'category' => ServiceCategory::SKINCARE_SPA->value,
                'duration' => 'P0Y0M0DT1H30M',
                'estimated_price' => 180.00,
                'created_at' => '2025-04-22T09:15+00:00',
                'updated_at' => '2025-04-22T09:15+00:00',
            ],
            [
                'organization_reference' => 'organization2',
                'name' => 'Zabieg oczyszczający twarz',
                'description' => 'Głębokie oczyszczenie i nawilżenie skóry twarzy.',
                'category' => ServiceCategory::SKINCARE_SPA->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 150.00,
                'created_at' => '2025-04-22T09:15+00:00',
                'updated_at' => '2025-04-22T09:15+00:00',
            ],
            [
                'organization_reference' => 'organization2',
                'name' => 'Depilacja woskiem',
                'description' => 'Usuwanie owłosienia woskiem twardym.',
                'category' => ServiceCategory::COSMETIC_TREATMENTS->value,
                'duration' => 'P0Y0M0DT0H40M',
                'estimated_price' => 80.00,
                'created_at' => '2025-04-22T09:15+00:00',
                'updated_at' => '2025-04-22T09:15+00:00',
            ],
            [
                'organization_reference' => 'organization3',
                'name' => 'Konsultacja stomatologiczna',
                'description' => 'Badanie jamy ustnej i plan leczenia.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT0H30M',
                'estimated_price' => 120.00,
                'created_at' => '2025-03-12T11:00+00:00',
                'updated_at' => '2025-03-12T11:00+00:00',
            ],
            [
                'organization_reference' => 'organization3',
                'name' => 'Higienizacja zębów',
                'description' => 'Skaling, piaskowanie i polerowanie zębów.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 200.00,
                'created_at' => '2025-03-12T11:00+00:00',
                'updated_at' => '2025-03-12T11:00+00:00',
            ],
            [
                'organization_reference' => 'organization3',
                'name' => 'Wybielanie zębów',
                'description' => 'Profesjonalne wybielanie lampą LED.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT1H30M',
                'estimated_price' => 600.00,
                'created_at' => '2025-03-12T11:00+00:00',
                'updated_at' => '2025-03-12T11:00+00:00',
            ],
            [
                'organization_reference' => 'organization4',
                'name' => 'Strzyżenie męskie',
                'description' => 'Klasyczne lub nowoczesne cięcie włosów.',
                'category' => ServiceCategory::BARBER->value,
                'duration' => 'P0Y0M0DT0H40M',
                'estimated_price' => 60.00,
                'created_at' => '2025-02-10T15:40+00:00',
                'updated_at' => '2025-02-10T15:40+00:00',
            ],
            [
                'organization_reference' => 'organization4',
                'name' => 'Golenie brzytwą',
                'description' => 'Tradycyjne golenie z gorącym ręcznikiem.',
                'category' => ServiceCategory::BARBER->value,
                'duration' => 'P0Y0M0DT0H45M',
                'estimated_price' => 70.00,
                'created_at' => '2025-02-10T15:40+00:00',
                'updated_at' => '2025-02-10T15:40+00:00',
            ],
            [
                'organization_reference' => 'organization4',
                'name' => 'Modelowanie brody',
                'description' => 'Stylizacja i pielęgnacja zarostu.',
                'category' => ServiceCategory::BARBER->value,
                'duration' => 'P0Y0M0DT0H30M',
                'estimated_price' => 50.00,
                'created_at' => '2025-02-10T15:40+00:00',
                'updated_at' => '2025-02-10T15:40+00:00',
            ],
            [
                'organization_reference' => 'organization5',
                'name' => 'Masaż gorącymi kamieniami',
                'description' => 'Zabieg odprężający i rozluźniający mięśnie.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT1H30M',
                'estimated_price' => 190.00,
                'created_at' => '2025-01-25T13:50+00:00',
                'updated_at' => '2025-01-25T13:50+00:00',
            ],
            [
                'organization_reference' => 'organization5',
                'name' => 'Sauna z aromaterapią',
                'description' => 'Relaks w saunie z naturalnymi olejkami eterycznymi.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 100.00,
                'created_at' => '2025-01-25T13:50+00:00',
                'updated_at' => '2025-01-25T13:50+00:00',
            ],
            [
                'organization_reference' => 'organization5',
                'name' => 'Terapia relaksacyjna',
                'description' => 'Sesja masażu i oddechu z elementami mindfulness.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT1H30M',
                'estimated_price' => 160.00,
                'created_at' => '2025-01-25T13:50+00:00',
                'updated_at' => '2025-01-25T13:50+00:00',
            ],
            [
                'organization_reference' => 'organization6',
                'name' => 'Trening personalny',
                'description' => 'Indywidualna sesja z trenerem personalnym.',
                'category' => ServiceCategory::FITNESS_AND_SPORTS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 120.00,
                'created_at' => '2025-06-10T10:05+00:00',
                'updated_at' => '2025-06-10T10:05+00:00',
            ],
            [
                'organization_reference' => 'organization6',
                'name' => 'Zajęcia fitness grupowe',
                'description' => 'Energetyczny trening w grupie z instruktorem.',
                'category' => ServiceCategory::FITNESS_AND_SPORTS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 40.00,
                'created_at' => '2025-06-10T10:05+00:00',
                'updated_at' => '2025-06-10T10:05+00:00',
            ],
            [
                'organization_reference' => 'organization7',
                'name' => 'Strzyżenie damskie',
                'description' => 'Modelowanie i cięcie włosów damskich.',
                'category' => ServiceCategory::HAIRDRESSER->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 100.00,
                'created_at' => '2025-04-03T14:20+00:00',
                'updated_at' => '2025-04-03T14:20+00:00',
            ],
            [
                'organization_reference' => 'organization7',
                'name' => 'Farbowanie włosów',
                'description' => 'Koloryzacja włosów pełna lub ombre.',
                'category' => ServiceCategory::HAIRDRESSER->value,
                'duration' => 'P0Y0M0DT2H',
                'estimated_price' => 220.00,
                'created_at' => '2025-04-03T14:20+00:00',
                'updated_at' => '2025-04-03T14:20+00:00',
            ],
            [
                'organization_reference' => 'organization8',
                'name' => 'Botox',
                'description' => 'Zabieg redukujący zmarszczki mimiczne.',
                'category' => ServiceCategory::COSMETIC_TREATMENTS->value,
                'duration' => 'P0Y0M0DT0H45M',
                'estimated_price' => 400.00,
                'created_at' => '2025-05-02T08:10+00:00',
                'updated_at' => '2025-05-02T08:10+00:00',
            ],
            [
                'organization_reference' => 'organization8',
                'name' => 'Peeling chemiczny',
                'description' => 'Zabieg poprawiający strukturę skóry.',
                'category' => ServiceCategory::COSMETIC_TREATMENTS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 250.00,
                'created_at' => '2025-05-02T08:10+00:00',
                'updated_at' => '2025-05-02T08:10+00:00',
            ],
            [
                'organization_reference' => 'organization9',
                'name' => 'Masaż antystresowy',
                'description' => 'Krótki masaż miejscowy na szyję i plecy.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT0H45M',
                'estimated_price' => 80.00,
                'created_at' => '2025-03-15T17:30+00:00',
                'updated_at' => '2025-03-15T17:30+00:00',
            ],
            [
                'organization_reference' => 'organization9',
                'name' => 'Rytuał spa (3 zabiegi)',
                'description' => 'Pakiet: peeling, masaż, maska relaksująca.',
                'category' => ServiceCategory::SKINCARE_SPA->value,
                'duration' => 'P0Y0M0DT2H30M',
                'estimated_price' => 350.00,
                'created_at' => '2025-03-15T17:30+00:00',
                'updated_at' => '2025-03-15T17:30+00:00',
            ],
            [
                'organization_reference' => 'organization10',
                'name' => 'Joga Vinyasa 60',
                'description' => 'Zajęcia jogi dla wszystkich poziomów.',
                'category' => ServiceCategory::FITNESS_AND_SPORTS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 30.00,
                'created_at' => '2025-07-21T09:00+00:00',
                'updated_at' => '2025-07-21T09:00+00:00',
            ],
            [
                'organization_reference' => 'organization10',
                'name' => 'Warsztat oddechowy',
                'description' => 'Praktyka oddechu i relaksacji.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT1H30M',
                'estimated_price' => 50.00,
                'created_at' => '2025-07-21T09:00+00:00',
                'updated_at' => '2025-07-21T09:00+00:00',
            ],
            [
                'organization_reference' => 'organization11',
                'name' => 'Manicure klasyczny',
                'description' => 'Pielęgnacja i pomalowanie paznokci.',
                'category' => ServiceCategory::NAILS->value,
                'duration' => 'P0Y0M0DT0H50M',
                'estimated_price' => 60.00,
                'created_at' => '2025-08-12T13:10+00:00',
                'updated_at' => '2025-08-12T13:10+00:00',
            ],
            [
                'organization_reference' => 'organization11',
                'name' => 'Stylizacja rzęs 1:1',
                'description' => 'Przedłużanie rzęs metodą klasyczną.',
                'category' => ServiceCategory::LASHES_AND_BROWS->value,
                'duration' => 'P0Y0M0DT1H30M',
                'estimated_price' => 180.00,
                'created_at' => '2025-08-12T13:10+00:00',
                'updated_at' => '2025-08-12T13:10+00:00',
            ],
            [
                'organization_reference' => 'organization12',
                'name' => 'Fizjoterapia pourazowa',
                'description' => 'Sesja rehabilitacyjna po urazie.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 120.00,
                'created_at' => '2025-09-05T10:30+00:00',
                'updated_at' => '2025-09-05T10:30+00:00',
            ],
            [
                'organization_reference' => 'organization12',
                'name' => 'Terapia manualna',
                'description' => 'Leczenie bólu mięśni i stawów.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT0H50M',
                'estimated_price' => 110.00,
                'created_at' => '2025-09-05T10:30+00:00',
                'updated_at' => '2025-09-05T10:30+00:00',
            ],
            [
                'organization_reference' => 'organization13',
                'name' => 'Konsultacja dermatologiczna',
                'description' => 'Ocena problemów skórnych i plan leczenia.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT0H30M',
                'estimated_price' => 140.00,
                'created_at' => '2025-05-30T11:15+00:00',
                'updated_at' => '2025-05-30T11:15+00:00',
            ],
            [
                'organization_reference' => 'organization13',
                'name' => 'Mikrodermabrazja',
                'description' => 'Zabieg złuszczający i wygładzający skórę.',
                'category' => ServiceCategory::SKINCARE_SPA->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 220.00,
                'created_at' => '2025-05-30T11:15+00:00',
                'updated_at' => '2025-05-30T11:15+00:00',
            ],
            [
                'organization_reference' => 'organization14',
                'name' => 'Masaż relaksacyjny',
                'description' => 'Masaż relaksujący całego ciała.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 120.00,
                'created_at' => '2025-02-16T16:00+00:00',
                'updated_at' => '2025-02-16T16:00+00:00',
            ],
            [
                'organization_reference' => 'organization14',
                'name' => 'Pakiet spa duo',
                'description' => 'Pakiet dla dwóch osób: masaż + sauna.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT2H',
                'estimated_price' => 250.00,
                'created_at' => '2025-02-16T16:00+00:00',
                'updated_at' => '2025-02-16T16:00+00:00',
            ],
            [
                'organization_reference' => 'organization15',
                'name' => 'Manicure profejsonalny z zdobieniami',
                'description' => 'Manicure z dodatkowymi zdobieniami.',
                'category' => ServiceCategory::NAILS->value,
                'duration' => 'P0Y0M0DT1H30M',
                'estimated_price' => 120.00,
                'created_at' => '2025-03-03T12:00+00:00',
                'updated_at' => '2025-03-03T12:00+00:00',
            ],
            [
                'organization_reference' => 'organization15',
                'name' => 'Pedicure SPA',
                'description' => 'Relaksujący pedicure z maską i masażem.',
                'category' => ServiceCategory::NAILS->value,
                'duration' => 'P0Y0M0DT1H20M',
                'estimated_price' => 140.00,
                'created_at' => '2025-03-03T12:00+00:00',
                'updated_at' => '2025-03-03T12:00+00:00',
            ],
            [
                'organization_reference' => 'organization16',
                'name' => 'Hydroterapia',
                'description' => 'Seans w basenie terapeutycznym.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT0H45M',
                'estimated_price' => 80.00,
                'created_at' => '2025-01-30T10:00+00:00',
                'updated_at' => '2025-01-30T10:00+00:00',
            ],
            [
                'organization_reference' => 'organization16',
                'name' => 'Konsultacja ortodontyczna',
                'description' => 'Ocena i plan leczenia ortodontycznego.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT0H40M',
                'estimated_price' => 130.00,
                'created_at' => '2025-01-30T10:00+00:00',
                'updated_at' => '2025-01-30T10:00+00:00',
            ],
            [
                'organization_reference' => 'organization17',
                'name' => 'Trening funkcjonalny',
                'description' => 'Zajęcia nastawione na poprawę sprawności.',
                'category' => ServiceCategory::FITNESS_AND_SPORTS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 45.00,
                'created_at' => '2025-06-14T09:00+00:00',
                'updated_at' => '2025-06-14T09:00+00:00',
            ],
            [
                'organization_reference' => 'organization17',
                'name' => 'Konsultacja dietetyczna',
                'description' => 'Analiza żywienia i plan dietetyczny.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT0H50M',
                'estimated_price' => 130.00,
                'created_at' => '2025-06-14T09:00+00:00',
                'updated_at' => '2025-06-14T09:00+00:00',
            ],
            [
                'organization_reference' => 'organization18',
                'name' => 'Pilates 55',
                'description' => 'Zajęcia pilates dla wszystkich poziomów.',
                'category' => ServiceCategory::FITNESS_AND_SPORTS->value,
                'duration' => 'P0Y0M0DT0H55M',
                'estimated_price' => 35.00,
                'created_at' => '2025-07-03T15:45+00:00',
                'updated_at' => '2025-07-03T15:45+00:00',
            ],
            [
                'organization_reference' => 'organization18',
                'name' => 'Trening rehabilitacyjny',
                'description' => 'Ćwiczenia przywracające sprawność po kontuzji.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 100.00,
                'created_at' => '2025-07-03T15:45+00:00',
                'updated_at' => '2025-07-03T15:45+00:00',
            ],
            [
                'organization_reference' => 'organization19',
                'name' => 'Strzyżenie damskie',
                'description' => 'Fryzura i modelowanie włosów.',
                'category' => ServiceCategory::HAIRDRESSER->value,
                'duration' => 'P0Y0M0DT1H10M',
                'estimated_price' => 110.00,
                'created_at' => '2025-04-09T14:00+00:00',
                'updated_at' => '2025-04-09T14:00+00:00',
            ],
            [
                'organization_reference' => 'organization19',
                'name' => 'Koloryzacja odrostu',
                'description' => 'Szybkie odświeżenie koloru.',
                'category' => ServiceCategory::HAIRDRESSER->value,
                'duration' => 'P0Y0M0DT1H30M',
                'estimated_price' => 160.00,
                'created_at' => '2025-04-09T14:00+00:00',
                'updated_at' => '2025-04-09T14:00+00:00',
            ],
            [
                'organization_reference' => 'organization20',
                'name' => 'Trening dla kobiet',
                'description' => 'Specjalistyczne zajęcia fitness dla kobiet.',
                'category' => ServiceCategory::FITNESS_AND_SPORTS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 40.00,
                'created_at' => '2025-09-20T09:20+00:00',
                'updated_at' => '2025-09-20T09:20+00:00',
            ],
            [
                'organization_reference' => 'organization20',
                'name' => 'Konsultacja z trenerem',
                'description' => 'Ocena wydolności i plan treningowy.',
                'category' => ServiceCategory::FITNESS_AND_SPORTS->value,
                'duration' => 'P0Y0M0DT0H45M',
                'estimated_price' => 80.00,
                'created_at' => '2025-09-20T09:20+00:00',
                'updated_at' => '2025-09-20T09:20+00:00',
            ],
            [
                'organization_reference' => 'organization21',
                'name' => 'Sauna + basen',
                'description' => 'Wejście do sauny i basenu z ręcznikiem.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT2H',
                'estimated_price' => 120.00,
                'created_at' => '2025-10-01T12:45+00:00',
                'updated_at' => '2025-10-01T12:45+00:00',
            ],
            [
                'organization_reference' => 'organization21',
                'name' => 'Zabieg na twarz z algami',
                'description' => 'Nawilżająca maska z alg morskich.',
                'category' => ServiceCategory::SKINCARE_SPA->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 210.00,
                'created_at' => '2025-10-01T12:45+00:00',
                'updated_at' => '2025-10-01T12:45+00:00',
            ],
            [
                'organization_reference' => 'organization22',
                'name' => 'Masaż klasyczny',
                'description' => 'Masaż leczniczy pleców i karku.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT0H50M',
                'estimated_price' => 90.00,
                'created_at' => '2025-03-19T16:15+00:00',
                'updated_at' => '2025-03-19T16:15+00:00',
            ],
            [
                'organization_reference' => 'organization22',
                'name' => 'Zabieg odnowy biologicznej',
                'description' => 'Pakiet zabiegów regenerujących skórę.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT1H30M',
                'estimated_price' => 200.00,
                'created_at' => '2025-03-19T16:15+00:00',
                'updated_at' => '2025-03-19T16:15+00:00',
            ],
            [
                'organization_reference' => 'organization23',
                'name' => 'Konsultacja naturopatyczna',
                'description' => 'Porady z zakresu medycyny naturalnej.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT0H45M',
                'estimated_price' => 100.00,
                'created_at' => '2025-01-17T09:35+00:00',
                'updated_at' => '2025-01-17T09:35+00:00',
            ],
            [
                'organization_reference' => 'organization23',
                'name' => 'Masaż limfatyczny',
                'description' => 'Pomoc przy obrzękach i detoksykacja.',
                'category' => ServiceCategory::WELLNESS->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 120.00,
                'created_at' => '2025-01-17T09:35+00:00',
                'updated_at' => '2025-01-17T09:35+00:00',
            ],
            [
                'organization_reference' => 'organization24',
                'name' => 'Solarium + manicure',
                'description' => 'Pakiet: solarium i szybki manicure.',
                'category' => ServiceCategory::OTHER->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 70.00,
                'created_at' => '2025-11-02T11:40+00:00',
                'updated_at' => '2025-11-02T11:40+00:00',
            ],
            [
                'organization_reference' => 'organization24',
                'name' => 'Zabieg na twarz z peelingiem',
                'description' => 'Oczyszczanie i nawilżenie skóry.',
                'category' => ServiceCategory::SKINCARE_SPA->value,
                'duration' => 'P0Y0M0DT1H',
                'estimated_price' => 130.00,
                'created_at' => '2025-11-02T11:40+00:00',
                'updated_at' => '2025-11-02T11:40+00:00',
            ],
            [
                'organization_reference' => 'organization25',
                'name' => 'Konsultacja pediatryczna',
                'description' => 'Badanie i porada dla dziecka.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT0H30M',
                'estimated_price' => 120.00,
                'created_at' => '2025-05-01T08:30+00:00',
                'updated_at' => '2025-05-01T08:30+00:00',
            ],
            [
                'organization_reference' => 'organization25',
                'name' => 'Rehabilitacja dziecięca',
                'description' => 'Zajęcia fizjoterapeutyczne dla dzieci.',
                'category' => ServiceCategory::HEALTHCARE->value,
                'duration' => 'P0Y0M0DT0H45M',
                'estimated_price' => 100.00,
                'created_at' => '2025-05-01T08:30+00:00',
                'updated_at' => '2025-05-01T08:30+00:00',
            ],
            [
                'organization_reference' => 'organization25',
                'name' => 'Terapia mowy',
                'description' => 'Zajęcia logopedyczne dla dzieci.',
                'category' => ServiceCategory::EDUCATION->value,
                'duration' => 'P0Y0M0DT0H45M',
                'estimated_price' => 90.00,
                'created_at' => '2025-05-01T08:30+00:00',
                'updated_at' => '2025-05-01T08:30+00:00',
            ],
        ];
    }
}