<?php 

declare(strict_types=1);

namespace App\DataFixtures\Demo\Organization\DataProvider;

class OrganizationDataProvider
{
    /** @return mixed[] */
    public static function getData(): array
    {
        return [
            [
                'name' => 'Studio Urody Bella',
                'description' => 'Gabinet kosmetyczny, pielęgnacja dłoni i stóp, oraz usługi spa.',
                'address_street' => 'Długa 45',
                'address_city' => 'Warszawa',
                'address_region' => 'Mazowieckie',
                'address_postal_code' => '00-238',
                'address_country' => 'Poland',
                'address_latitude' => 52.247851,
                'address_longitude' => 21.004757,
                'place_id' => 'ChIJG7i5gA9YQEARE1J57qL5g-E',
                'formatted_address' => 'Długa 45, 00-238 Warszawa, Poland',
                'created_at' => '2025-04-22T09:15+02:00',
                'updated_at' => '2025-04-22T09:15+02:00',
            ],
            [
                'name' => 'Healthy Smile Dental',
                'description' => 'Nowoczesny gabinet stomatologiczny z pełnym zakresem usług dentystycznych.',
                'address_street' => 'Piotrkowska 121',
                'address_city' => 'Łódź',
                'address_region' => 'Łódzkie',
                'address_postal_code' => '90-430',
                'address_country' => 'Poland',
                'address_latitude' => 51.763246,
                'address_longitude' => 19.456992,
                'place_id' => 'ChIJyQ-Qk7D3GEcRE-4e3yL781Q',
                'formatted_address' => 'Piotrkowska 121, 90-430 Łódź, Poland',
                'created_at' => '2025-03-12T11:00+01:00',
                'updated_at' => '2025-03-12T11:00+01:00',
            ],
            [
                'name' => 'City Barber Shop',
                'description' => 'Tradycyjny salon fryzjerski i barbershop dla mężczyzn.',
                'address_street' => 'Wrocławska 22',
                'address_city' => 'Poznań',
                'address_region' => 'Wielkopolskie',
                'address_postal_code' => '60-201',
                'address_country' => 'Poland',
                'address_latitude' => 52.408271,
                'address_longitude' => 16.934426,
                'place_id' => 'ChIJl7E173r6GEcR2N2t-gQ-G30',
                'formatted_address' => 'Wrocławska 22, 60-201 Poznań, Poland',
                'created_at' => '2025-02-10T15:40+01:00',
                'updated_at' => '2025-02-10T15:40+01:00',
            ],
            [
                'name' => 'Zen Wellness Center',
                'description' => 'Centrum masażu i relaksu oferujące terapie manualne i aromaterapię.',
                'address_street' => 'Starowiejska 18',
                'address_city' => 'Gdynia',
                'address_region' => 'Pomorskie',
                'address_postal_code' => '81-356',
                'address_country' => 'Poland',
                'address_latitude' => 54.5189,
                'address_longitude' => 18.5394,
                'place_id' => 'ChIJuU2r9rVvQUcRj8E7k4g9R_I',
                'formatted_address' => 'Starowiejska 18, 81-356 Gdynia, Poland',
                'created_at' => '2025-01-25T13:50+01:00',
                'updated_at' => '2025-01-25T13:50+01:00',
            ],
            [
                'name' => 'Elite Fitness Club',
                'description' => 'Siłownia i klub fitness z nowoczesnym sprzętem i zajęciami grupowymi.',
                'address_street' => 'Warszawska 99',
                'address_city' => 'Białystok',
                'address_region' => 'Podlaskie',
                'address_postal_code' => '15-062',
                'address_country' => 'Poland',
                'address_latitude' => 53.132488,
                'address_longitude' => 23.16884,
                'place_id' => 'ChIJ_1g0-91J4EcRg8O4O1q8wI0',
                'formatted_address' => 'Warszawska 99, 15-062 Białystok, Poland',
                'created_at' => '2025-06-10T10:05+02:00',
                'updated_at' => '2025-06-10T10:05+02:00',
            ],
            [
                'name' => 'Hair & Style Studio',
                'description' => 'Profesjonalny salon fryzjerski damski, koloryzacja i strzyżenia.',
                'address_street' => 'Kościuszki 10',
                'address_city' => 'Katowice',
                'address_region' => 'Śląskie',
                'address_postal_code' => '40-049',
                'address_country' => 'Poland',
                'address_latitude' => 50.259907,
                'address_longitude' => 19.021585,
                'place_id' => 'ChIJQ4f2jQd_GEcRS6pYm0E9GGE',
                'formatted_address' => 'Kościuszki 10, 40-049 Katowice, Poland',
                'created_at' => '2025-04-03T14:20+02:00',
                'updated_at' => '2025-04-03T14:20+02:00',
            ],
            [
                'name' => 'Medika Clinic',
                'description' => 'Centrum medycyny estetycznej i kosmetologii high-tech.',
                'address_street' => 'Mickiewicza 33',
                'address_city' => 'Rzeszów',
                'address_region' => 'Podkarpackie',
                'address_postal_code' => '35-065',
                'address_country' => 'Poland',
                'address_latitude' => 50.03723,
                'address_longitude' => 22.00496,
                'place_id' => 'ChIJQ4f2jQd_GEcRS6pYm0E9GHE',
                'formatted_address' => 'Mickiewicza 33, 35-065 Rzeszów, Poland',
                'created_at' => '2025-05-02T08:10+02:00',
                'updated_at' => '2025-05-02T08:10+02:00',
            ],
            [
                'name' => 'Golden Touch Spa',
                'description' => 'Luksusowe spa oferujące masaże gorącymi kamieniami i zabiegi na ciało.',
                'address_street' => 'Sienkiewicza 11',
                'address_city' => 'Kielce',
                'address_region' => 'Świętokrzyskie',
                'address_postal_code' => '25-333',
                'address_country' => 'Poland',
                'address_latitude' => 50.87033,
                'address_longitude' => 20.62752,
                'place_id' => 'ChIJf5nJ_9e-BEcRQo_F56Q2dJ8',
                'formatted_address' => 'Sienkiewicza 11, 25-333 Kielce, Poland',
                'created_at' => '2025-03-15T17:30+01:00',
                'updated_at' => '2025-03-15T17:30+01:00',
            ],
            [
                'name' => 'Yoga Flow Studio',
                'description' => 'Studio jogi i mindfulness, zajęcia dla początkujących i zaawansowanych.',
                'address_street' => 'Nowowiejska 7',
                'address_city' => 'Wrocław',
                'address_region' => 'Dolnośląskie',
                'address_postal_code' => '50-315',
                'address_country' => 'Poland',
                'address_latitude' => 51.108977,
                'address_longitude' => 17.03854,
                'place_id' => 'ChIJ_f973K6HGEcR6cM4k5M7j0w',
                'formatted_address' => 'Nowowiejska 7, 50-315 Wrocław, Poland',
                'created_at' => '2025-07-21T09:00+02:00',
                'updated_at' => '2025-07-21T09:00+02:00',
            ],
            [
                'name' => 'Perfect Look Salon',
                'description' => 'Kompleksowy salon urody i stylizacji paznokci (manicure, pedicure).',
                'address_street' => 'Grochowska 77',
                'address_city' => 'Warszawa',
                'address_region' => 'Mazowieckie',
                'address_postal_code' => '04-126',
                'address_country' => 'Poland',
                'address_latitude' => 52.24112,
                'address_longitude' => 21.08545,
                'place_id' => 'ChIJF2E4eXnCGEcR72yT1c5vC4M',
                'formatted_address' => 'Grochowska 77, 04-126 Warszawa, Poland',
                'created_at' => '2025-08-12T13:10+02:00',
                'updated_at' => '2025-08-12T13:10+02:00',
            ],
            [
                'name' => 'Rehab Plus',
                'description' => 'Gabinet fizjoterapii, rehabilitacji po urazach i terapii bólu.',
                'address_street' => 'Lubicz 15',
                'address_city' => 'Kraków',
                'address_region' => 'Małopolskie',
                'address_postal_code' => '31-034',
                'address_country' => 'Poland',
                'address_latitude' => 50.065,
                'address_longitude' => 19.952,
                'place_id' => 'ChIJx8x9d5eCEkcRHc6j0xM5qJ0',
                'formatted_address' => 'Lubicz 15, 31-034 Kraków, Poland',
                'created_at' => '2025-09-05T10:30+02:00',
                'updated_at' => '2025-09-05T10:30+02:00',
            ],
            [
                'name' => 'Pure Skin Clinic',
                'description' => 'Klinika dermatologiczna i centrum zabiegów anti-aging.',
                'address_street' => 'Aleje Jerozolimskie 221',
                'address_city' => 'Warszawa',
                'address_region' => 'Mazowieckie',
                'address_postal_code' => '02-486',
                'address_country' => 'Poland',
                'address_latitude' => 52.17965,
                'address_longitude' => 20.9408,
                'place_id' => 'ChIJ894b-9rCGEcR02mR72N3wVw',
                'formatted_address' => 'Aleje Jerozolimskie 221, 02-486 Warszawa, Poland',
                'created_at' => '2025-05-30T11:15+02:00',
                'updated_at' => '2025-05-30T11:15+02:00',
            ],
            [
                'name' => 'Harmony Spa',
                'description' => 'Oaza relaksu z jacuzzi, sauną i szeroką ofertą masaży.',
                'address_street' => 'Piastowska 12',
                'address_city' => 'Opole',
                'address_region' => 'Opolskie',
                'address_postal_code' => '45-081',
                'address_country' => 'Poland',
                'address_latitude' => 50.675,
                'address_longitude' => 17.922,
                'place_id' => 'ChIJA2l_05t1FEcR5y4B8XmQ35A',
                'formatted_address' => 'Piastowska 12, 45-081 Opole, Poland',
                'created_at' => '2025-02-16T16:00+01:00',
                'updated_at' => '2025-02-16T16:00+01:00',
            ],
            [
                'name' => 'Diamond Nails',
                'description' => 'Ekskluzywna stylizacja paznokci, manicure hybrydowy i przedłużanie rzęs.',
                'address_street' => 'Chrobrego 8',
                'address_city' => 'Szczecin',
                'address_region' => 'Zachodniopomorskie',
                'address_postal_code' => '70-563',
                'address_country' => 'Poland',
                'address_latitude' => 53.4285,
                'address_longitude' => 14.5528,
                'place_id' => 'ChIJQ-P6B8s8REcRs8Q0sQ1M09A',
                'formatted_address' => 'Bolesława Chrobrego 8, 70-563 Szczecin, Poland',
                'created_at' => '2025-03-03T12:00+01:00',
                'updated_at' => '2025-03-03T12:00+01:00',
            ],
            [
                'name' => 'Aqua Beauty',
                'description' => 'Spa wodne, zabiegi na twarz i ciało oraz masaże relaksacyjne.',
                'address_street' => '3 Maja 27',
                'address_city' => 'Toruń',
                'address_region' => 'Kujawsko-Pomorskie',
                'address_postal_code' => '87-100',
                'address_country' => 'Poland',
                'address_latitude' => 53.0138,
                'address_longitude' => 18.5984,
                'place_id' => 'ChIJ_1g0-91J4EcRg8O4O1q8vH1',
                'formatted_address' => '3 Maja 27, 87-100 Toruń, Poland',
                'created_at' => '2025-01-30T10:00+01:00',
                'updated_at' => '2025-01-30T10:00+01:00',
            ],
            [
                'name' => 'Smile Zone Dental',
                'description' => 'Nowoczesna klinika dentystyczna, ortodoncja i wybielanie zębów.',
                'address_street' => 'Kołątaja 9',
                'address_city' => 'Gdańsk',
                'address_region' => 'Pomorskie',
                'address_postal_code' => '80-895',
                'address_country' => 'Poland',
                'address_latitude' => 54.352,
                'address_longitude' => 18.646,
                'place_id' => 'ChIJm74_V8vBGEcRNh8N0gN0w5M',
                'formatted_address' => 'Kołątaja 9, 80-895 Gdańsk, Poland',
                'created_at' => '2025-06-14T09:00+02:00',
                'updated_at' => '2025-06-14T09:00+02:00',
            ],
            [
                'name' => 'Body Balance Studio',
                'description' => 'Studio fitness i pilates, treningi personalne i dietetyka.',
                'address_street' => 'Słowackiego 88',
                'address_city' => 'Bydgoszcz',
                'address_region' => 'Kujawsko-Pomorskie',
                'address_postal_code' => '85-008',
                'address_country' => 'Poland',
                'address_latitude' => 53.1235,
                'address_longitude' => 18.0084,
                'place_id' => 'ChIJq7E174r6GEcR8O4O1q8wA0B',
                'formatted_address' => 'Słowackiego 88, 85-008 Bydgoszcz, Poland',
                'created_at' => '2025-07-03T15:45+02:00',
                'updated_at' => '2025-07-03T15:45+02:00',
            ],
            [
                'name' => 'Luna Hair Studio',
                'description' => 'Fryzjer i stylistka włosów, specjalizacja w upięciach ślubnych.',
                'address_street' => 'Kościuszki 5',
                'address_city' => 'Lublin',
                'address_region' => 'Lubelskie',
                'address_postal_code' => '20-530',
                'address_country' => 'Poland',
                'address_latitude' => 51.2465,
                'address_longitude' => 22.5684,
                'place_id' => 'ChIJ-9rCGEcR02mR72N3gVw',
                'formatted_address' => 'Kościuszki 5, 20-530 Lublin, Poland',
                'created_at' => '2025-04-09T14:00+02:00',
                'updated_at' => '2025-04-09T14:00+02:00',
            ],
            [
                'name' => 'Silhouette Fitness',
                'description' => 'Studio fitness tylko dla kobiet, zajęcia cardio i siłowe.',
                'address_street' => 'Piłsudskiego 102',
                'address_city' => 'Olsztyn',
                'address_region' => 'Warmińsko-Mazurskie',
                'address_postal_code' => '10-450',
                'address_country' => 'Poland',
                'address_latitude' => 53.7784,
                'address_longitude' => 20.4801,
                'place_id' => 'ChIJYwB3PzM4PEcRj8E7k4g9R_Z',
                'formatted_address' => 'Piłsudskiego 102, 10-450 Olsztyn, Poland',
                'created_at' => '2025-09-20T09:20+02:00',
                'updated_at' => '2025-09-20T09:20+02:00',
            ],
            [
                'name' => 'Royal Spa & Wellness',
                'description' => 'Luksusowe spa z basenem, jacuzzi, sauną i gabinetami masażu.',
                'address_street' => 'Kopernika 4',
                'address_city' => 'Sopot',
                'address_region' => 'Pomorskie',
                'address_postal_code' => '81-704',
                'address_country' => 'Poland',
                'address_latitude' => 54.4416,
                'address_longitude' => 18.5614,
                'place_id' => 'ChIJo43rV8vBGEcRTh8N0gN0w5O',
                'formatted_address' => 'Kopernika 4, 81-704 Sopot, Poland',
                'created_at' => '2025-10-01T12:45+02:00',
                'updated_at' => '2025-10-01T12:45+02:00',
            ],
            [
                'name' => 'Relax Point',
                'description' => 'Gabinet masażu klasycznego, sportowego i relaksacyjnego.',
                'address_street' => 'Mickiewicza 21',
                'address_city' => 'Gliwice',
                'address_region' => 'Śląskie',
                'address_postal_code' => '44-100',
                'address_country' => 'Poland',
                'address_latitude' => 50.2945,
                'address_longitude' => 18.6714,
                'place_id' => 'ChIJG_x9d5eCEkcR3c6j0xM5qA0',
                'formatted_address' => 'Mickiewicza 21, 44-100 Gliwice, Poland',
                'created_at' => '2025-03-19T16:15+01:00',
                'updated_at' => '2025-03-19T16:15+01:00',
            ],
            [
                'name' => 'Green Health Clinic',
                'description' => 'Centrum medycyny naturalnej, ziołolecznictwa i akupunktury.',
                'address_street' => 'Żeromskiego 8',
                'address_city' => 'Radom',
                'address_region' => 'Mazowieckie',
                'address_postal_code' => '26-600',
                'address_country' => 'Poland',
                'address_latitude' => 51.4025,
                'address_longitude' => 21.1471,
                'place_id' => 'ChIJ0_q6A8s8REcRs8Q0sQ1M04A',
                'formatted_address' => 'Żeromskiego 8, 26-600 Radom, Poland',
                'created_at' => '2025-01-17T09:35+01:00',
                'updated_at' => '2025-01-17T09:35+01:00',
            ],
            [
                'name' => 'Sunshine Beauty',
                'description' => 'Salon urody, makijaż permanentny, pielęgnacja twarzy i solarium.',
                'address_street' => 'Nowa 12',
                'address_city' => 'Zielona Góra',
                'address_region' => 'Lubuskie',
                'address_postal_code' => '65-001',
                'address_country' => 'Poland',
                'address_latitude' => 51.939,
                'address_longitude' => 15.505,
                'place_id' => 'ChIJo5nJ_9e-BEcRQo_F56Q2dT8',
                'formatted_address' => 'Nowa 12, 65-001 Zielona Góra, Poland',
                'created_at' => '2025-11-02T11:40+01:00',
                'updated_at' => '2025-11-02T11:40+01:00',
            ],
            [
                'name' => 'Euphoria Wellness',
                'description' => 'Centrum odnowy biologicznej, hydroterapia i masaże lecznicze.',
                'address_street' => 'Reymonta 16',
                'address_city' => 'Bielsko-Biała',
                'address_region' => 'Śląskie',
                'address_postal_code' => '43-300',
                'address_country' => 'Poland',
                'address_latitude' => 49.8224,
                'address_longitude' => 19.0443,
                'place_id' => 'ChIJv8O4O1q8wI0_f973K6HGEcR',
                'formatted_address' => 'Władysława Reymonta 16, 43-300 Bielsko-Biała, Poland',
                'created_at' => '2025-07-11T10:10+02:00',
                'updated_at' => '2025-07-11T10:10+02:00',
            ],
            [
                'name' => 'Happy Kids Clinic',
                'description' => 'Klinika pediatryczna, rehabilitacja dziecięca i opieka psychologiczna.',
                'address_street' => 'Armii Krajowej 55',
                'address_city' => 'Tarnów',
                'address_region' => 'Małopolskie',
                'address_postal_code' => '33-100',
                'address_country' => 'Poland',
                'address_latitude' => 50.012,
                'address_longitude' => 20.985,
                'place_id' => 'ChIJQ4f2jQd_GEcRS6pYm0E9G2G',
                'formatted_address' => 'Armii Krajowej 55, 33-100 Tarnów, Poland',
                'created_at' => '2025-05-01T08:30+02:00',
                'updated_at' => '2025-05-01T08:30+02:00',
            ],
        ];

    }
}