<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJArwi4l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJArwi4l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJArwi4l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJArwi4l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJArwi4l\App_KernelDevDebugContainer([
    'container.build_hash' => 'JArwi4l',
    'container.build_id' => '7135f44d',
    'container.build_time' => 1679695176,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJArwi4l');
